[firebase]
type = "service_account"
project_id = "aharonilabinventory"
private_key_id = "d6f7531b46fcf33ef9ad988582e7817d348f55c2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDK7dWjMNeXQvo7
2wvxL9XQojOHyGlyAO5PSwHYLFX67CYRDwGEYLjNc4gqXgZtTtxLbs/+Ap3iLtnv
COD0prZ/DZbrFqA2NCd25gdIj10/Jd9y3JXcaDNNqVpvG7Ty2oeuNST7bWxfsF+N
ZAVU6if1m58djVdS1AALMbNFG7cZYo3FljbQmKPbCOM9VSqrY42YEGng1O9DUBnk
jBoUZfgGyFhy4cf2487Ucsr9rVnmDpU4umi/xE5Rs6zuT24+Dk2lhTQ85ag0SUwz
oDv6WZ6d7JRVKe9MwAUJNWrVlP9XjZafO+eXdPw8KrroyqXM5CPftZyRd0P5tmZW
9Y6wVXvnAgMBAAECggEAK5T2q+yicKb+zPoXT35BgmRDgubk1ooipD7sr3ueH5y1
9DXv0nlfVyh31vmIkdM89qpe2yO+usPrJC4Y+hIP4auOfQDH+bwruZpfeBLqKNS+
b5G2UbbDReuYM4KU0w9h0mUxgxoWC1r6uof/qSP83v/EJXmkhnJnbAAJi08PfNDO
0PkX2BQDowUAeW69ch9H1/8sQWda2PNCcBktuwwEdx7veauNebMx5lyUEHsEjtZ3
PGl4VLeRMBhDPlRMSf2TwzUWuDUzd+r0ziUD5U/ry2QhYoevA+NHhrgrUY+avdln
3oe0kmh+wXiykKCVff8K1/hMl78RtB5pUAXDcFcU+QKBgQDkXaHZDjgm8e48kFy5
oVvdPzt+FA0rEbkWd1ULVtVXurSC8zrRPehDYLm5HwiyhuihVEKkERLB3eHJrQYD
4W7tqR2UdszkiNuB7szVzvCAvn+5kSQUJLXjCWfdC269gidKxcxjQ2Id/2z07D1e
Qd0rQuza9IFc6QTDEQQHjHe5RQKBgQDjfDfLI/WnuaOnhcn9rGbZvQx/+CX1enfn
hPCGzBVyIgAuBzV8BRadvUSC9p0kLqhqdsxB7GiBmaSvBpVXHQVFKYOwoQMk9OIz
O0e7B7XZ4RmTEt4oyrEl8jQikxz1G3Ch4Y4pjHTFyvcjd+btZDQnWyiGiWoQHNwZ
fTdcy8C1OwKBgHvbkMGh5bCxvM3aWoBP1PxNpF3AUFgQt7tIo7aPtQxs9iSj+T2t
fwC0QGb4PwZdB2UgxzgnDm5ZgnGYx09pgHmkJKf2OzCkTbHOLAi2wViCedHSt6e5
NXFbE5se7UQZiGgUmcMos9mjRJweWTZ7MJKbLM2gmV0kAPIvk2jotbKlAoGBAMlf
Rox+kpEc1fAPkNUL7ifFH/GQGxoIhWfe2ISa2EkmK/6Sxxe38WNFDgbYhBZpbxB/
hSS+P2yqM4v0SfLJb8bfjwGmJoBqfmpXiZHYq3PpvZfh1eNKOjKbCueoTrPyzGug
nRXOjfghSVCObU+rqjdEjMU7kzYcNgIiRAXTIA3NAoGBAMJoQlMKFrrDJck/Acqj
7L1XtuZgKeE4q05FBYD84GLMmaDukNw68ZPuUHnkDVvNa7G3RgSn7hfhNfXBnwPi
kPVO4gBWn5/Jaa2UuiMumWO7IpxMSSgHTObL6YMeGNGwHk9GdvSU+1wjX/biBJid
3jbp4JQVFRUYcrjggzKkVn6U
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fu6uk@aharonilabinventory.iam.gserviceaccount.com"
client_id = "103585799880841348560"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fu6uk%40aharonilabinventory.iam.gserviceaccount.com"

[auth]
username = "aharonilab-inventory"
password = "p0lh4!Wu#AS#Eq^q6YlR"